# 公開するページのURL
baseURL = "https://genichiro22.github.io/gh-blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true
disqusShortname = "genichiro22"

# ブログのタイトル
title = "ビリヤニの律"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Genichiro"
    bio = "分析、AWS、MLシステム、IoTあたりに関心があります。独学中心なので気ままに。"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  github = "genichiro22"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

